export const EXCHANGE_ABI = [
  {
    name: "openLong",
    type: "function",
    inputs: [
      { name: "pxToken", type: "address" },
      { name: "collateral", type: "uint256" },
      { name: "leverage", type: "uint256" },
      { name: "pythUpdateData", type: "bytes[]" },
    ],
    outputs: [{ name: "positionId", type: "bytes32" }],
    stateMutability: "payable",
  },
  {
    name: "openShort",
    type: "function",
    inputs: [
      { name: "pxToken", type: "address" },
      { name: "collateral", type: "uint256" },
      { name: "leverage", type: "uint256" },
      { name: "pythUpdateData", type: "bytes[]" },
    ],
    outputs: [{ name: "positionId", type: "bytes32" }],
    stateMutability: "payable",
  },
  {
    name: "closeLong",
    type: "function",
    inputs: [
      { name: "positionId", type: "bytes32" },
      { name: "pythUpdateData", type: "bytes[]" },
    ],
    outputs: [{ name: "pnl", type: "int256" }],
    stateMutability: "payable",
  },
  {
    name: "closeShort",
    type: "function",
    inputs: [
      { name: "positionId", type: "bytes32" },
      { name: "pythUpdateData", type: "bytes[]" },
    ],
    outputs: [{ name: "pnl", type: "int256" }],
    stateMutability: "payable",
  },
  {
    name: "getPosition",
    type: "function",
    inputs: [{ name: "positionId", type: "bytes32" }],
    outputs: [
      { name: "trader", type: "address" },
      { name: "pxToken", type: "address" },
      { name: "isLong", type: "bool" },
      { name: "collateral", type: "uint256" },
      { name: "notional", type: "uint256" },
      { name: "entryPrice", type: "uint256" },
      { name: "openedAt", type: "uint256" },
      { name: "borrowAccumulator", type: "uint256" },
    ],
    stateMutability: "view",
  },
  {
    name: "getUnrealizedPnl",
    type: "function",
    inputs: [
      { name: "positionId", type: "bytes32" },
      { name: "pythUpdateData", type: "bytes[]" },
    ],
    outputs: [
      { name: "pnl", type: "int256" },
      { name: "collateralRemaining", type: "uint256" },
      { name: "isLiquidatable", type: "bool" },
    ],
    stateMutability: "payable",
  },
  {
    name: "marketOpen",
    type: "function",
    inputs: [],
    outputs: [{ type: "bool" }],
    stateMutability: "view",
  },
  {
    name: "getPoolConfig",
    type: "function",
    inputs: [{ name: "pxToken", type: "address" }],
    outputs: [
      {
        type: "tuple",
        components: [
          { name: "xStock", type: "address" },
          { name: "pythFeedId", type: "bytes32" },
          { name: "totalLiquidity", type: "uint256" },
          { name: "totalBorrowed", type: "uint256" },
          { name: "lpTotalSupply", type: "uint256" },
          { name: "borrowAccumulator", type: "uint256" },
          { name: "lastAccrualTime", type: "uint256" },
          { name: "lpToken", type: "address" },
          { name: "maxLeverage", type: "uint256" },
        ],
      },
    ],
    stateMutability: "view",
  },
  {
    name: "usdc",
    type: "function",
    inputs: [],
    outputs: [{ type: "address" }],
    stateMutability: "view",
  },
  {
    name: "TRADING_FEE_BPS",
    type: "function",
    inputs: [],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    name: "getOpenPositionCount",
    type: "function",
    inputs: [{ name: "pxToken", type: "address" }],
    outputs: [{ type: "uint256" }],
    stateMutability: "view",
  },
  {
    name: "PositionOpened",
    type: "event",
    inputs: [
      { name: "positionId", type: "bytes32", indexed: true },
      { name: "trader", type: "address", indexed: true },
      { name: "pxToken", type: "address", indexed: false },
      { name: "isLong", type: "bool", indexed: false },
      { name: "collateral", type: "uint256", indexed: false },
      { name: "notional", type: "uint256", indexed: false },
      { name: "entryPrice", type: "uint256", indexed: false },
    ],
  },
  {
    name: "PositionClosed",
    type: "event",
    inputs: [
      { name: "positionId", type: "bytes32", indexed: true },
      { name: "trader", type: "address", indexed: true },
      { name: "pnl", type: "int256", indexed: false },
    ],
  },
] as const;
